packages/examples/src/utils/hooks.js, packages/lib/src/Container.tsx, packages/lib/src/hooks/use-component.tsx, packages/lib/src/hooks/use-script.tsx, packages/lib/src/scripts/orbit-controls/orbit-camera.js, packages/lib/src/scripts/post/index.js, packages/lib/src/scripts/shadow-catcher/index.js, packages/lib/src/utils/picker.tsx
This PR fixes an issue whereby assets we're not correctly removed if the Applicaiton was destroyed. It uses the `app.root.uuid` as a cache key, so if this changes the cache will invalidate
=> Fix Script cleanup in useScript hook

packages/examples/src/GlbViewer.jsx, packages/lib/src/components/Camera.tsx, packages/lib/src/utils/color.ts
This PR adds support for declaring color properties using CSS hex strings including [X11 color names](https://en.wikipedia.org/wiki/X11_color_names). 
This allows users to do things like
```jsx
<Application fog='#ff3322' >
<Camera clearColor='#rebeccapurple' />
</Application>
```
Components that expose color properties, can opt-in and accept css hex colors with the `useColor` hook by declaring properties that are colors
```jsx
const colors = useColors(props, ['ambient', 'diffuse', ... ])
const mappedProps = { ...props, ...colors }
```
=> CSS Color Support

eslint.config.mjs, package-lock.json, package.json
Adds the new [React Compiler](https://react.dev/learn/react-compiler) and associated [EsLint plugin](https://www.npmjs.com/package/eslint-plugin-react-compiler) which catches a number of performance issues. Needs subsequent PR to fix these.
=> Add's ESLint React compiler

package.json, packages/docs/src/components/editor.tsx
This fixes an issue preventing the Playground from updating during editing.
It used the `MDXClient` instead of the `MDXClientAsync` which was intended for server side rendering
=> Fix Playground Live Preview

packages/docs/src/app/docs/page.mdx, packages/lib/src/utils/picker.tsx
This fixes a crash when toggling between the `Demo` and `Code`  Tab in the docs. It was caused when the Application was hidden and the async read in webgl-graphics-device threw an error. This error is now caught gracefully.
Also updates the styling so the canvas does not lose it's dimensions when toggling back
=> Fix docs crash

packages/lib/src/Application.tsx, packages/lib/src/Entity.tsx, packages/lib/src/contexts/pointer-events-context.tsx, packages/lib/src/utils/picker.tsx
Optimizes the Picker to only run when a `onPointer*` prop is passed to a child entity. This should improve performance for non interactive apps
- Introduced a new `PointerEventsContext` to manage pointer event registrations across components.
- Updated `Application.tsx` to provide the `PointerEventsContext` to child components.
- Modified `Entity.tsx` to utilize the context for adding and removing pointer event listeners dynamically.
- Enhanced `usePicker` utility to check for registered pointer events before processing interactions.
These changes improve the handling of pointer events, allowing for more flexible and efficient interaction management within the application.
=> Implement Pointer Events Context for Enhanced Interaction Handling

packages/lib/src/components/GSplat.tsx
- Updated the GSplat component to accept optional `vertex` and `fragment` props for shader customization.
- Modified the asset instantiation logic to utilize the provided shaders, improving flexibility for rendering assets.
These changes enhance the rendering capabilities of the GSplat component, allowing for more dynamic visual effects.
=> Enhance GSplat component to support custom vertex and fragment shaders

packages/docs/next.config.js, packages/docs/src/app/_meta.global.ts, packages/docs/src/app/docs/page.mdx, packages/docs/src/app/examples/[[...mdxPath]]/page.tsx, packages/docs/src/content/primitives.mdx, packages/docs/src/docs-components/Editor.tsx, packages/docs/src/docs-components/Playground.tsx, packages/docs/src/docs-components/code-error-boundary.tsx
Docs update
- Renamed routes `/playround ` -> `/examples`
- Added an Error Boundary to flag Monaco errors when live editing
- Added Examples links to both header and side nav
- Fixes CSS pointer event issue blocking buttons
=> Docs update

packages/docs/src/docs-components/Playground.tsx
Ensures context menu doesn't block mouse events in exampes.
Fixes #63
=> Add context menu prevention in Playground component

.github/workflows/publish.yml, package-lock.json, package.json, packages/docs/src/app/_meta.global.ts, packages/docs/src/components/EnvAtlas.tsx, packages/docs/src/content/splats.mdx, packages/lib/package.json
Adds example to show how to load Gaussian Splats
=> Add Splat Viewer example 

package-lock.json, packages/docs/src/app/docs/api/components/collision/page.mdx, packages/docs/src/app/docs/api/components/rigidbody/page.mdx, packages/docs/src/content/physics.mdx, packages/lib/package.json, packages/lib/src/Application.tsx, packages/lib/src/components/Collision.tsx, packages/lib/src/components/RigidBody.tsx, packages/lib/src/contexts/physics-context.tsx, packages/lib/src/hooks/use-component.tsx, packages/lib/src/utils/warn-once.ts
This PR introduces a new context for managing physics. The `usePhysics` prop in the `<Application/>` now lazily loads the physics lib as well as instantiating the library. This allows for efficient code-splitting resulting in a lower build size when `usePhysics` is disabled (default).
Before an example build size was
```bash
dist/assets/index-BygGqKn2.css     23.37 kB │ gzip:   6.16 kB
dist/assets/index-PLmK4POJ.js   3,799.09 kB │ gzip: 966.60 kB
```
This now gets split into
```bash
dist/assets/ammo.module-BZQ5nLDI.js  1,905.09 kB │ gzip: 434.59 kB
dist/assets/index-BSzaSobb.js        2,100.68 kB │ gzip: 582.38 kB
```
Ammo is now an optional peer dep, so it will need to be installed when required.
Fixes #83 
* [`packages/lib/src/contexts/physics-context.tsx`](diffhunk://#diff-15dda40574d02 …
=> Lazy Physics

packages/lib/package.json, renovate.json
PlayCanvas engine can introduce [breaking changes in minor updates](https://github.com/playcanvas/react/issues/88#issuecomment-2772519920). This PR locks the dependancy to the patch range which makes things safer at the cost of new features
Also separates PlayCanvas out in renovate.json as a separate dependancy.
=> Limit PlayCanvas versions to patch range

package-lock.json, packages/docs/src/app/layout.tsx, packages/lib/package.json
- Bump version of @playcanvas/react to 0.3.0 in package.json and package-lock.json.
- Update layout banner to reflect the new version and highlight support for React 19.
- Improve documentation to provide clearer information about the new release.
=> Update @playcanvas/react to version 0.3.0 and enhance documentation

packages/lib/src/utils/color.ts, packages/lib/src/utils/validation.ts
This PR removes the redundant useColor hook and allows color props to be specified as arrays
```javascript
useMaterial({ diffuse: [1, 0, 0], emissive: 'red');
```
Fixes #109 
- Removed the custom `useColors` hook to streamline color processing.
- Updated color validation to support array format for colors in the validation schema.
- Enhanced error messages for better clarity on expected color formats.
- Cleaned up unused imports and improved type definitions for CSS colors.
=> Refactor color utilities and validation logic

packages/lib/src/utils/color.ts, packages/lib/src/utils/types-utils.ts
This PR broaden the color type of components to support string. Closes #110 
- Removed unused type definitions related to CSS colors in color.ts.
- Updated the Serializable type in types-utils.ts to replace CssColor with string for better type consistency.
These changes streamline the color utility functions and enhance type safety across the codebase.
=> Allow string color types

package.json, packages/lib/package.json
- Added license information as "MIT" to both package.json files for compliance.
- Updated repository URLs to point to the main repository instead of specific directories, improving clarity and accessibility.
=> Update package metadata and repository links

package-lock.json, packages/lib/package.json
- Bumped the version of the @playcanvas/react package from 0.3.0 to 0.3.1 in both package.json and package-lock.json.
- Added license information as "MIT" to ensure compliance and clarity across the project.
=> Update package version to 0.3.1 

packages/lib/src/components/Script.test.tsx, packages/lib/src/components/Script.tsx, packages/lib/src/hooks/use-script.tsx, packages/lib/src/utils/types-utils.ts
This PR updates the Script component to support ref forwarding.
```tsx
function Test(){
const scriptRef = useRef()
useEffect(() => console.log(scriptRef.current.speed)) // logs 10!  
return <Script script={TestScript} speed={10} />
}
```
It also adds test for the Script Component
Fixes #126
- Introduced comprehensive unit tests for the Script component, validating prop passing, ref forwarding, initialization, re-rendering behavior, and cleanup on unmount.
- Refactored the useScript hook to support ref forwarding, enhancing the integration with the Script component.
- Updated type definitions to improve type safety and clarity in the codebase.
These changes enhance the testing coverage and improve the overall functionality of the Script component and its associated hooks.
=> Support ref forwading for Script Component

package-lock.json, packages/docs/app/layout.tsx, packages/lib/package.json
- Bumped the version of the @playcanvas/react package from 0.3.1 to 0.3.2 in package.json and package-lock.json.
- Updated the banner in the documentation layout to reflect the new version and provide a link to the release notes.
- Added a prepare script to the package.json for improved build process.
These changes ensure that the package is up-to-date and that the documentation accurately reflects the latest release.
=> @playcanvas/react version 0.3.2 

packages/docs/content/docs/api/hooks.mdx, packages/lib/src/hooks/index.ts, packages/lib/src/hooks/use-frame.test.tsx, packages/lib/src/hooks/use-frame.tsx
Adds a new `useFrame` hook. This is a more react friendly approach to respond to frame updates.
```tsx
import { useFrame } from '@playcanvas/react/hooks'
const SpinningComponent = () => {
const entityRef = useRef(null);
useFrame((dt) => {
entityRef.current.rotate(0, dt, 0);
})
return <Entity ref={entityRef}>>
}
```
- Introduced the `useFrame` hook to register a callback on every frame update, improving performance for frame-based calculations.
- Added unit tests for the `useFrame` hook to ensure proper registration and unregistration of callbacks during component lifecycle.
- Updated the hooks docs to export the new `useFrame` hook.
These changes enhance the functionality of the hooks library and provide a robust testing framework for the new feature.
=> Add `useFrame` hook and associated tests

package-lock.json, packages/docs/app/layout.tsx, packages/docs/components.json, packages/docs/components/ui/card.tsx, packages/docs/components/ui/dialog.tsx, packages/docs/components/ui/drawer.tsx, packages/docs/components/ui/separator.tsx, packages/docs/components/ui/switch.tsx, packages/docs/components/ui/table.tsx, packages/docs/components/ui/tabs.tsx, packages/docs/components/ui/toggle-group.tsx, packages/docs/components/ui/toggle.tsx, packages/docs/content/blocks.mdx, packages/docs/package.json, packages/docs/registry/splat-viewer/camera-mode-toggle.tsx, packages/docs/registry/splat-viewer/controls.tsx, packages/docs/registry/splat-viewer/download-button.tsx, packages/docs/registry/splat-viewer/help-button.tsx, packages/docs/registry/splat-viewer/help-dialog.tsx, packages/docs/registry/splat-viewer/index.tsx, packages/docs/registry/splat-viewer/menu-button.tsx, packages/docs/registry/splat-viewer/smart-camera.tsx, packages/docs/registry/splat-viewer/splat-viewer-context.tsx, packages/docs/registry/splat-viewer/splat-viewer.tsx, packages/docs/registry/splat-viewer/timeline.tsx, packages/docs/registry/splat-viewer/utils/effects.tsx, packages/docs/registry/splat-viewer/utils/pose.ts
This PR introduces a **Help** and **Settings** panel for the **Splat Viewer** Block.
The **Help** panel provides users with guidance on how to interact with the viewer, including keyboard shortcuts and control tips, accessible via a dialog on desktop or a drawer on mobile.
The panel is triggered via "?" key command, primary "Help" button or via the secondary actions menu
https://github.com/user-attachments/assets/1c8fea11-caaf-4ce9-8eb4-e4f146963205
On mobile, the dialog collapses to an animated dismissible card, with background fade
https://github.com/user-attachments/assets/993c3dd7-8d8f-47f9-9a74-700abc88e701
The **Settings** panel follows similar behaviour. It contains duplicates of many of the primary actions such as "Download", "FullScreen" and links to help. It also contains a …
=> Help/Settings & Improved Mobile Layout

package.json, packages/blocks/src/splat-viewer/hooks/use-render-on-camera-change.tsx, packages/blocks/src/splat-viewer/smart-camera.tsx, packages/blocks/src/splat-viewer/splat-viewer.tsx, packages/docs/package.json, pnpm-lock.yaml
Adds a new hook which ensures the app is only rendering when the camera changes.
- Introduced a new hook, useRenderOnCameraChange, to optimize rendering when the camera changes in the SmartCamera component.
- Updated SmartCamera to utilize the new hook and set app.renderNextFrame to true for immediate rendering.
- Modified SplatViewer to also set app.renderNextFrame to true, ensuring consistent rendering behavior across components.
- Adjusted Application component in SplatViewer to disable autoRender for better control over rendering flow.
Fixes #138
=> Disable SplatViewer Auto Render

.github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/lint.yml, .github/workflows/publish.yml, .github/workflows/test.yml, package.json, packages/blocks/package.json, packages/blocks/src/splat-viewer/hooks/use-render-on-camera-change.tsx, packages/blocks/src/splat-viewer/smart-camera.tsx, packages/blocks/src/splat-viewer/splat-viewer.tsx, packages/docs/content/_meta.tsx, packages/docs/next.config.js, packages/docs/package.json, packages/lib/package.json, pnpm-lock.yaml
This pull request introduces several updates across the project, including dependency management, configuration updates, and code cleanup. Key changes include the addition of `pnpm` as the package manager, updates to dependencies and package configurations, and the removal of unnecessary debug logs.
* Added `pnpm@10.11.0` as the package manager in the root `package.json` and `packages/docs/package.json`. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R6) [[2]](diffhunk://#diff-5926d0c6229942021583ce21a7c24dcc3d5f10e744bf6d560b5bee2d85635792R7)
* Introduced `next@15.3.1` as a dependency in the root `package.json` and updated the `pnpm-lock.yaml` to reflect this addition. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b64815 …
=> Updates PNPM deps

packages/blocks/README.md, packages/blocks/src/splat-viewer/utils/style.ts, packages/docs/components/Check.tsx, packages/docs/content/blocks/getting-started.mdx, packages/docs/content/blocks/index.mdx, packages/docs/content/blocks/splat-viewer.mdx, packages/docs/content/docs/index.mdx, packages/docs/registry.json, packages/docs/registry/splat-viewer.tsx
This pull request introduces several updates and improvements to the PlayCanvas Blocks project, focusing on documentation enhancements, new components, and minor adjustments to styles and functionality. Key changes include the addition of new documentation pages, updates to the vignette intensity in the style utilities, and the introduction of a new `Block` component.
* Added a new "Getting Started" guide in `packages/docs/content/blocks/getting-started.mdx`, detailing installation instructions for PlayCanvas Blocks and Tailwind v4.
* Introduced a new "Blocks" documentation page (`packages/docs/content/blocks/index.mdx`), highlighting features, usage, and the "Splat Viewer" block.
* Renamed and updated the `splat-viewer` documentation file …
=> Seperates Blocks home pages

packages/blocks/src/splat-viewer/hooks/use-render-on-camera-change.tsx, packages/blocks/src/splat-viewer/smart-camera.tsx, packages/blocks/src/splat-viewer/splat-viewer.tsx, packages/blocks/src/splat-viewer/utils/effects.tsx, packages/blocks/src/splat-viewer/utils/style.ts, packages/docs/components/ThemedSplatViewer.tsx
This PR introduces a new `variant` prop to The `<Viewer.splat/>` block, allowing users to apply predefined visual styles to Splats vis post-processing presets - or supply a fully custom visual configuration.
**Example**
```tsx
<Viewer.Splat src="./splat.ply" variant="noir" />
```
where the type signature is:
```tsx
variant : "paris" | "neutral" | "noir" | "none" | PostEffectsSettings;
```  
- The string values map to built-in style presets.
- `"none"` disables all post effects.
- Defaults to `"neutral"`
- Option to pass a full PostEffectsSettings object for custom control.
**Styles**
`"noir"`
`"neutral"`
`"paris"`
`"none"`
- Introduced a new `variant` prop for `SmartCamera` to allow selection of different post-processing styles: 'paris', 'neutral', 'noir', and 'none'.
- Updated …
=> Adds Splat Viewer style variants

packages/blocks/src/splat-viewer/hooks/use-render-on-camera-change.tsx
This PR adds an `IntersectionObserver` to the `<SplatViewer/>`which prevents rendering when the viewer is outside the viewport. This happens regardless of camera animation or movement.
=> Adds SplatViewer IntersectionObserver guard.

packages/lib/src/components/GSplat.tsx
This PR updates the `<Gsplat/>` component to use the new [GSplatResource API](https://github.com/playcanvas/engine/pull/7734)
=> Updates GSplat Component to new API

packages/docs/components/hooks/use-asset.ts, packages/docs/content/docs/api/hooks/use-asset.mdx, packages/lib/src/hooks/use-asset.ts
This PR adds zero config support for Draco compressed GLB's.
Calling `useModel` with a Draco compressed mesh will automatically lazy load the Draco Decoder library. Custom paths to the draco decoder can be set using the `dracoInitialize()` method.
Fixes #133
=> Zero Config Draco Support

.changeset/orange-bikes-give.md, packages/blocks/src/index.ts, packages/docs/content/blocks/splat-viewer.mdx
This PR exposes the `useAssetViewer` hook as public API which exposes API and context for the Viewer. This provides more user flexibility for creating custom controls.
Fixes #170. 
```tsx
import { Viewer, useAssetViewer } from "@playcanvas/blocks";
// Create a Custom Progress Bar
const CustomProgressBar = () => {
// get the loading progress subscription
const { subscribe } = useAssetViewer();
useEffect(() => {
// when the component mounts, subscribe to the progress
return subscribe((progress) => console.log(progress));
});
}
// Create a custom Button the toggles the fullscreen
const CustomFullScreenButton = () = {
const { toggleFullScreen } = useAssetViewer();
return <button onClick={() => toggleFullScreen} />
}
export default () => (
<Viewer.Splat src={splatUrl} >
<MyCustomProgressBar/> …
```
=> useAssetViewer Hook

.changeset/new-teams-move.md, packages/lib/src/Application.tsx, packages/lib/src/utils/env.ts, packages/lib/src/utils/validation.ts
Ensures the NODE_ENV check is compatible outside Node, defaulting to `production' in browser
```javascript
import { env } from './env'
if (env === 'development') {
console.log('works outside Node');
}
```
=> Fix NODE_ENV var in browser

.changeset/bumpy-grapes-give.md, packages/blocks/tsconfig.json, packages/lib/tsconfig.json, tsconfig.json
TS source  is now inline in the source map itself (not the JS file). This was previously breaking view source map, as the TS source was not being distributed in the NPM package.
=> Fix source maps

.changeset/yellow-ways-unite.md, packages/lib/src/utils/validation.ts
Ensures `<Light/>` component color updates are correctly assigned on the component and not simply `.set()`. This fixes a regression with the prop validation which would prevent the light colors from updating after being initially set.
See this [forum issue](https://forum.playcanvas.com/t/react-directional-light/40352).
=> Fixes light color assignment

.changeset/easy-cars-beam.md, packages/blocks/src/splat-viewer/progress-indicator.tsx, packages/blocks/src/splat-viewer/smart-camera.tsx, packages/docs/app/[[...mdxPath]]/page.tsx, packages/docs/app/layout.tsx, packages/docs/components/Grid.tsx, packages/docs/content/docs/index.mdx, packages/docs/docs-components/Playground.tsx, packages/lib/package.json, pnpm-lock.yaml
Minor fixes for docs
- Updates docs with new Getting started `npm create playcanvas -t react-ts` guide
- Update release banner to 0.5.0
- Replaces internal Grid with playcanvas as per https://github.com/playcanvas/react/pull/193
- Fixes some types issues in @playcanvas/blocks
- Fixes layout issues in playground code editor
- Adds gsplat.org to docs
=> Chore docs fixes

.changeset/bumpy-pears-add.md, packages/lib/src/utils/picker.tsx
Prevents the picker from running if there are no bound pointer events in the tree
=> Check for bound pointerEvents in the onInteractionEvent callback

.changeset/common-cities-sink.md, packages/lib/src/components/Collision.tsx
This ensures the type exported by Collision follows the same pattern as other components, so that `Vec3 => [number, number number]'
- Changed the CollisionProps interface to extend from Serializable<PublicProps<CollisionComponent>> for improved type safety and serialization support.
Fixes #226
=> fix(Collision): update TypeScript definitions for CollisionProps 

.changeset/open-berries-attend.md, packages/docs/content/docs/api/hooks/index.mdx, packages/lib/src/contexts/physics-context.tsx, packages/lib/src/hooks/index.ts
This PR exposes a new `usePhysics` hook which provides info on the loading state of the physics engine.
This is useful in scenarios where you have imperative scripts that depend upon the Physics being loaded. See https://github.com/playcanvas/react/issues/223#issuecomment-3257837551
```tsx
import { usePhysics } from '@playcanvas/react/hooks'
const PhysicsAwareScript = () => {
const { isPhysicsLoaded } = usePhysics();
return isPhysicsLoaded && <Script script={FirstPersonController} />
}
```
The hook has the following shape
```tsx
export interface PhysicsContext {
/**
* Whether physics is enabled on the application.
*/
isPhysicsEnabled: boolean;
/**
* Whether the physics library has been successfully loaded.
*/
isPhysicsLoaded: boolean;
/**
* The error that occurred when loading physics, if …
```
=> Expose `usePhysics` hook

.github/workflows/changesets.yml, packages/blocks/package.json, packages/lib/package.json
Removes the pre-publish script in `packages/lib` and `packages/blocks` instead using workflow to build directly
- Added a step to build packages for publishing in the GitHub Actions workflow.
- Removed the `prepublishOnly` script from the blocks and lib package.json files for a cleaner build process.
=> Remove CI Prepublish

.changeset/easy-friends-wash.md, packages/lib/src/utils/validation.ts
This PR ensures that any engine property defined via a setter is called in the correct way. This was preventing internal values from updating
❌ before
```tsx
collision.halfExtents.fromArray(value)
```
✅  Fix
```tsx
collision.halfExtents = value
```
=> Fix setter assignment
